### ISSUE TITLE
Support for sdformat14 and Gazebo Harmonic

### ISSUE THREAD

**Issue by quarkytale** [ros/sdformat_urdf#24]
Once Rolling rolls over for ROS 2 Jazzy, we'll default to using `sdformat14`.

How should we handle branches in `sdformat_urdf`? Currently, there's a `galactic` and a `ros2` branch, where the former supports Galactic and everything below. So one option is creating an `iron` branch and updating `ros2` to support newer defaults. 

@sloretz How are things typically done in the ROS 2 ecosystem or any other more preferable options?

CC: @azeey

**Comment by sloretz** [comment]
> How are things typically done in the ROS 2 ecosystem or any other more preferable options?

I think the approach that's [become recommended is to make a `rolling` branch](https://discourse.ros.org/t/change-default-branch-name-to-rolling-in-ros-2-core/26009), and then branch off that as distros are released. The version of gazebo to be supported on each ROS distro is specified by by [REP 2000](https://www.ros.org/reps/rep-2000.html#rolling-ridley-june-2020-ongoing).

I'd recommend the following goals:
* `rolling` branch supports Gazebo Harmonic
* `iron` branch supports Gazebo Fortress
* `humble` branch supports Gazebo Fortress.

If we don't have the time for all those goals, then I'd recommend the priority being updating Rolling first, then Humble since it's LTS, and lastly Iron as a nice to have.

I think we could get there by doing the following:

1. Create a branch called `rolling` pointing to the same commit as `ros2`
1. Update the `rolling` branch until it supports Gazebo Fortress (unless it does already, then no work to do here)
1. Create a `humble` branch and an `iron` branch off of `rolling`
1. Update the `rolling` branch to support Gazebo Harmonic

There will be some cleanup work too of updating source branch entries in [ros/rosdistro](https://github.com/ros/rosdistro) and making bloom releases.
