### ISSUE TITLE
`sdformat_urdf` is Disabled on the ROS buildfarm

### ISSUE THREAD

**Issue by Amronos** [ros/sdformat_urdf#36]
`sdformat_urdf` is disabled on the ROS buildfarm but is needed for the tests of https://github.com/ros-controls/ros2_control/pull/1763, can it be enabled? More info can be found [here](https://github.com/ros-controls/ros2_control/pull/1763#issuecomment-2423042725).

**Comment by sloretz** [comment]
`sdformat_urdf` is blacklisted on RHEL 9 because `sdformat` is not packaged for RHEL https://github.com/ros2/ros_buildfarm_config/blame/2e5343f0f35129f3c411bfb64a4e7a470e33c37c/jazzy/release-rhel-build.yaml#L56

I'd recommend either:

* asking the `sdformat` maintainers what it would take to package it for RHEL https://github.com/gazebosim/sdformat/issues
* asking the `ros2_control` maintainers if they're ok with using preprocessor macros and conditional dependencies to make sdformat support optional


I'll close this as not-planned until `sdformat` is available on RHEL.

**Comment by azeey** [comment]
Looks like `gz_tools_vendor` is not being built on RHEL (https://build.ros2.org/job/Jsrc_el9__gz_tools_vendor__rhel_9__source/). I'm going to look into it.

**Comment by azeey** [comment]
@sloretz `sdformat` is now available on RHEL for Jazzy and Rolling (see https://build.ros2.org/job/Jbin_rhel_el964__sdformat_vendor__rhel_9_x86_64__binary/ and https://build.ros2.org/job/Rbin_rhel_el964__sdformat_vendor__rhel_9_x86_64__binary/). Would you mind removing `sdformat_urdf` and `sdformat_test_files` from the black list for those releases?

**Comment by azeey** [comment]
I actually went ahead and created https://github.com/ros2/ros_buildfarm_config/pull/312. Let me know if there's anything else that needs to be done.
